### PR TITLE
provide Government regulations to users

### PR DESCRIPTION
**Pull request by JeffreyCHChan**

### CODE REVIEW

**Comment by JeffreyCHChan** [comment]
test for rendering frontend needs to be done still @narroarrow

**Review by alexbara2000 — APPROVED** [review]
It's good

**Comment by malhimaira** [comment]
This looks okay, can we add the tests pls and @alexbara2000 ill let you decide if u wanna merge before or after

**Comment by alexbara2000** [comment]
@malhimaira  take a look at the file changes.

**Pull request merged**
