### PR TITLE
Automated patient update reminder

### PR DESCRIPTION
**Pull request by JeffreyCHChan**
- Added an automated email for patients who have not provided an update for the day.
- Manually tested with multiple times and ensuring the appropriate patients are emailed

### CODE REVIEW

**Comment by malhimaira** [comment]
Hey @JeffreyCHChan , can we accept the page once the font-end side is complete?

**Comment by JeffreyCHChan** [comment]
There is no front end part to this. @malhimaira  this part of development is strictly backend and doesn’t need front end

**Review by malhimaira — COMMENTED** [review]
Seems ok with me as I just see spacing fixes and some new queries. If you could pls push the backend test for these, I will then approve!

**Comment by malhimaira** [comment]
So I will accept this considering that a timer is not sufficient to attach a unit test alone, please ensure to see what can be done for integration tests.

**Pull request merged**
