### PR TITLE
autofill patient info & urgent request 

### PR DESCRIPTION
**Pull request by JeffreyCHChan**
test for urgent request works

### CODE REVIEW

**Comment by alexbara2000** [comment]
I see 2 files for file manipulation on Doctor and patient side have been added. Since those features are not done can we delete those from this pull request and put them in a separate branch?

**Comment by JeffreyCHChan** [comment]
i think we committed them while working on the symptoms form things so they became entangled

**Comment by JeffreyCHChan** [comment]
i'm still fixing some rebasing and conflicts right now tho

**Review by alexbara2000 — APPROVED** [review]
Everything looks good on my side and I rebased/ solved the merge conflits. once merged into pre release please retest all the features you worked on. Thanks!

**Review by malhimaira — APPROVED** [review]
Looks good, some parts were refractored to fix merge conflicts.

**Pull request merged**
